"""Agregando beneficiario

Revision ID: 3082aa82a8ee
Revises: db5feb34a857
Create Date: 2025-07-13 14:34:38.556369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3082aa82a8ee'
down_revision = 'db5feb34a857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('titular_id', sa.Integer(), nullable=False),
    sa.Column('dropbox_folder_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['titular_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiario')
    # ### end Alembic commands ###
