#!/usr/bin/env python3
"""
Utilidades para países y nacionalidades
"""

def get_countries_list():
    """Retorna una lista de países ordenados alfabéticamente"""
    return [
        ("AF", "Afganistán"),
        ("AL", "Albania"),
        ("DE", "Alemania"),
        ("AD", "Andorra"),
        ("AO", "Angola"),
        ("AI", "Anguila"),
        ("AQ", "Antártida"),
        ("AG", "Antigua y Barbuda"),
        ("SA", "Arabia Saudita"),
        ("DZ", "Argelia"),
        ("AR", "Argentina"),
        ("AM", "Armenia"),
        ("AW", "Aruba"),
        ("AU", "Australia"),
        ("AT", "Austria"),
        ("AZ", "Azerbaiyán"),
        ("BS", "Bahamas"),
        ("BD", "Bangladés"),
        ("BB", "Barbados"),
        ("BH", "Baréin"),
        ("BE", "Bélgica"),
        ("BZ", "Belice"),
        ("BJ", "Benín"),
        ("BM", "Bermudas"),
        ("BY", "Bielorrusia"),
        ("BO", "Bolivia"),
        ("BA", "Bosnia y Herzegovina"),
        ("BW", "Botsuana"),
        ("BR", "Brasil"),
        ("BN", "Brunéi"),
        ("BG", "Bulgaria"),
        ("BF", "Burkina Faso"),
        ("BI", "Burundi"),
        ("BT", "Bután"),
        ("CV", "Cabo Verde"),
        ("KH", "Camboya"),
        ("CM", "Camerún"),
        ("CA", "Canadá"),
        ("TD", "Chad"),
        ("CL", "Chile"),
        ("CN", "China"),
        ("CY", "Chipre"),
        ("VA", "Ciudad del Vaticano"),
        ("CO", "Colombia"),
        ("KM", "Comoras"),
        ("CG", "Congo"),
        ("CD", "Congo (RDC)"),
        ("KR", "Corea del Sur"),
        ("CI", "Costa de Marfil"),
        ("CR", "Costa Rica"),
        ("HR", "Croacia"),
        ("CU", "Cuba"),
        ("CW", "Curazao"),
        ("DK", "Dinamarca"),
        ("DJ", "Yibuti"),
        ("DM", "Dominica"),
        ("EC", "Ecuador"),
        ("EG", "Egipto"),
        ("SV", "El Salvador"),
        ("AE", "Emiratos Árabes Unidos"),
        ("ER", "Eritrea"),
        ("SK", "Eslovaquia"),
        ("SI", "Eslovenia"),
        ("ES", "España"),
        ("US", "Estados Unidos"),
        ("EE", "Estonia"),
        ("ET", "Etiopía"),
        ("PH", "Filipinas"),
        ("FI", "Finlandia"),
        ("FJ", "Fiyi"),
        ("FR", "Francia"),
        ("GA", "Gabón"),
        ("GM", "Gambia"),
        ("GE", "Georgia"),
        ("GH", "Ghana"),
        ("GI", "Gibraltar"),
        ("GD", "Granada"),
        ("GR", "Grecia"),
        ("GL", "Groenlandia"),
        ("GP", "Guadalupe"),
        ("GU", "Guam"),
        ("GT", "Guatemala"),
        ("GF", "Guayana Francesa"),
        ("GG", "Guernsey"),
        ("GN", "Guinea"),
        ("GQ", "Guinea Ecuatorial"),
        ("GW", "Guinea-Bisáu"),
        ("GY", "Guyana"),
        ("HT", "Haití"),
        ("HN", "Honduras"),
        ("HK", "Hong Kong"),
        ("HU", "Hungría"),
        ("IN", "India"),
        ("ID", "Indonesia"),
        ("IQ", "Irak"),
        ("IR", "Irán"),
        ("IE", "Irlanda"),
        ("IS", "Islandia"),
        ("IL", "Israel"),
        ("IT", "Italia"),
        ("JM", "Jamaica"),
        ("JP", "Japón"),
        ("JE", "Jersey"),
        ("JO", "Jordania"),
        ("KZ", "Kazajistán"),
        ("KE", "Kenia"),
        ("KG", "Kirguistán"),
        ("KI", "Kiribati"),
        ("XK", "Kosovo"),
        ("KW", "Kuwait"),
        ("LA", "Laos"),
        ("LS", "Lesoto"),
        ("LV", "Letonia"),
        ("LB", "Líbano"),
        ("LR", "Liberia"),
        ("LY", "Libia"),
        ("LI", "Liechtenstein"),
        ("LT", "Lituania"),
        ("LU", "Luxemburgo"),
        ("MO", "Macao"),
        ("MK", "Macedonia del Norte"),
        ("MG", "Madagascar"),
        ("MY", "Malasia"),
        ("MW", "Malaui"),
        ("MV", "Maldivas"),
        ("ML", "Malí"),
        ("MT", "Malta"),
        ("MA", "Marruecos"),
        ("MQ", "Martinica"),
        ("MU", "Mauricio"),
        ("MR", "Mauritania"),
        ("YT", "Mayotte"),
        ("MX", "México"),
        ("FM", "Micronesia"),
        ("MD", "Moldavia"),
        ("MC", "Mónaco"),
        ("MN", "Mongolia"),
        ("ME", "Montenegro"),
        ("MS", "Montserrat"),
        ("MZ", "Mozambique"),
        ("MM", "Myanmar"),
        ("NA", "Namibia"),
        ("NR", "Nauru"),
        ("NP", "Nepal"),
        ("NI", "Nicaragua"),
        ("NE", "Níger"),
        ("NG", "Nigeria"),
        ("NU", "Niue"),
        ("NF", "Isla Norfolk"),
        ("NO", "Noruega"),
        ("NC", "Nueva Caledonia"),
        ("NZ", "Nueva Zelanda"),
        ("OM", "Omán"),
        ("NL", "Países Bajos"),
        ("PK", "Pakistán"),
        ("PW", "Palaos"),
        ("PS", "Palestina"),
        ("PA", "Panamá"),
        ("PG", "Papúa Nueva Guinea"),
        ("PY", "Paraguay"),
        ("PE", "Perú"),
        ("PF", "Polinesia Francesa"),
        ("PL", "Polonia"),
        ("PT", "Portugal"),
        ("PR", "Puerto Rico"),
        ("GB", "Reino Unido"),
        ("CF", "República Centroafricana"),
        ("CZ", "República Checa"),
        ("DO", "República Dominicana"),
        ("RE", "Reunión"),
        ("RW", "Ruanda"),
        ("RO", "Rumania"),
        ("RU", "Rusia"),
        ("EH", "Sahara Occidental"),
        ("SB", "Islas Salomón"),
        ("WS", "Samoa"),
        ("AS", "Samoa Americana"),
        ("BL", "San Bartolomé"),
        ("KN", "San Cristóbal y Nieves"),
        ("SM", "San Marino"),
        ("MF", "San Martín"),
        ("PM", "San Pedro y Miquelón"),
        ("VA", "Santa Sede"),
        ("VC", "San Vicente y las Granadinas"),
        ("SH", "Santa Elena"),
        ("LC", "Santa Lucía"),
        ("ST", "Santo Tomé y Príncipe"),
        ("SN", "Senegal"),
        ("RS", "Serbia"),
        ("SC", "Seychelles"),
        ("SL", "Sierra Leona"),
        ("SG", "Singapur"),
        ("SY", "Siria"),
        ("SO", "Somalia"),
        ("LK", "Sri Lanka"),
        ("SZ", "Suazilandia"),
        ("ZA", "Sudáfrica"),
        ("SD", "Sudán"),
        ("SS", "Sudán del Sur"),
        ("SE", "Suecia"),
        ("CH", "Suiza"),
        ("SR", "Surinam"),
        ("TH", "Tailandia"),
        ("TZ", "Tanzania"),
        ("TJ", "Tayikistán"),
        ("IO", "Territorio Británico del Océano Índico"),
        ("TF", "Territorios Australes Franceses"),
        ("TL", "Timor Oriental"),
        ("TG", "Togo"),
        ("TK", "Tokelau"),
        ("TO", "Tonga"),
        ("TT", "Trinidad y Tobago"),
        ("TN", "Túnez"),
        ("TM", "Turkmenistán"),
        ("TR", "Turquía"),
        ("TV", "Tuvalu"),
        ("UA", "Ucrania"),
        ("UG", "Uganda"),
        ("UY", "Uruguay"),
        ("UZ", "Uzbekistán"),
        ("VU", "Vanuatu"),
        ("VE", "Venezuela"),
        ("VN", "Vietnam"),
        ("WF", "Wallis y Futuna"),
        ("YE", "Yemen"),
        ("DJ", "Yibuti"),
        ("ZM", "Zambia"),
        ("ZW", "Zimbabue")
    ]

def get_nationalities_list():
    """Retorna una lista de nacionalidades ordenadas alfabéticamente"""
    return [
        ("Afgana", "Afgana"),
        ("Albanesa", "Albanesa"),
        ("Alemana", "Alemana"),
        ("Andorrana", "Andorrana"),
        ("Angoleña", "Angoleña"),
        ("Antiguana", "Antiguana"),
        ("Argelina", "Argelina"),
        ("Argentina", "Argentina"),
        ("Armenia", "Armenia"),
        ("Australiana", "Australiana"),
        ("Austriaca", "Austriaca"),
        ("Azerbaiyana", "Azerbaiyana"),
        ("Bahameña", "Bahameña"),
        ("Bangladesí", "Bangladesí"),
        ("Barbadense", "Barbadense"),
        ("Belga", "Belga"),
        ("Beliceña", "Beliceña"),
        ("Beninesa", "Beninesa"),
        ("Bielorrusa", "Bielorrusa"),
        ("Boliviana", "Boliviana"),
        ("Bosnia", "Bosnia"),
        ("Botsuanesa", "Botsuanesa"),
        ("Brasileña", "Brasileña"),
        ("Búlgara", "Búlgara"),
        ("Burkinesa", "Burkinesa"),
        ("Burundesa", "Burundesa"),
        ("Camboyana", "Camboyana"),
        ("Camerunesa", "Camerunesa"),
        ("Canadiense", "Canadiense"),
        ("Chilena", "Chilena"),
        ("China", "China"),
        ("Chipriota", "Chipriota"),
        ("Colombiana", "Colombiana"),
        ("Comorense", "Comorense"),
        ("Congoleña", "Congoleña"),
        ("Costarricense", "Costarricense"),
        ("Croata", "Croata"),
        ("Cubana", "Cubana"),
        ("Danesa", "Danesa"),
        ("Dominicana", "Dominicana"),
        ("Ecuatoguineana", "Ecuatoguineana"),
        ("Ecuatoriana", "Ecuatoriana"),
        ("Egipcia", "Egipcia"),
        ("Salvadoreña", "Salvadoreña"),
        ("Emiratí", "Emiratí"),
        ("Eritrea", "Eritrea"),
        ("Eslovaca", "Eslovaca"),
        ("Eslovena", "Eslovena"),
        ("Española", "Española"),
        ("Estadounidense", "Estadounidense"),
        ("Estonia", "Estonia"),
        ("Etíope", "Etíope"),
        ("Filipina", "Filipina"),
        ("Finlandesa", "Finlandesa"),
        ("Fiyiana", "Fiyiana"),
        ("Francesa", "Francesa"),
        ("Gabonesa", "Gabonesa"),
        ("Gambiana", "Gambiana"),
        ("Georgiana", "Georgiana"),
        ("Ghanesa", "Ghanesa"),
        ("Granadina", "Granadina"),
        ("Griega", "Griega"),
        ("Guatemalteca", "Guatemalteca"),
        ("Guineana", "Guineana"),
        ("Guyanesa", "Guyanesa"),
        ("Haitiana", "Haitiana"),
        ("Hondureña", "Hondureña"),
        ("Húngara", "Húngara"),
        ("India", "India"),
        ("Indonesia", "Indonesia"),
        ("Iraquí", "Iraquí"),
        ("Iraní", "Iraní"),
        ("Irlandesa", "Irlandesa"),
        ("Islandesa", "Islandesa"),
        ("Israelí", "Israelí"),
        ("Italiana", "Italiana"),
        ("Jamaiquina", "Jamaiquina"),
        ("Japonesa", "Japonesa"),
        ("Jordana", "Jordana"),
        ("Kazaja", "Kazaja"),
        ("Keniata", "Keniata"),
        ("Kirguisa", "Kirguisa"),
        ("Kuwaití", "Kuwaití"),
        ("Laosiana", "Laosiana"),
        ("Lesotense", "Lesotense"),
        ("Letona", "Letona"),
        ("Libanesa", "Libanesa"),
        ("Liberiana", "Liberiana"),
        ("Libia", "Libia"),
        ("Liechtensteiniana", "Liechtensteiniana"),
        ("Lituana", "Lituana"),
        ("Luxemburguesa", "Luxemburguesa"),
        ("Macedonia", "Macedonia"),
        ("Madagascareña", "Madagascareña"),
        ("Malasia", "Malasia"),
        ("Malauí", "Malauí"),
        ("Maldiva", "Maldiva"),
        ("Maliense", "Maliense"),
        ("Maltesa", "Maltesa"),
        ("Marroquí", "Marroquí"),
        ("Mauriciana", "Mauriciana"),
        ("Mauritana", "Mauritana"),
        ("Mexicana", "Mexicana"),
        ("Moldava", "Moldava"),
        ("Monegasca", "Monegasca"),
        ("Mongola", "Mongola"),
        ("Montenegrina", "Montenegrina"),
        ("Mozambiqueña", "Mozambiqueña"),
        ("Namibia", "Namibia"),
        ("Nepalí", "Nepalí"),
        ("Nicaragüense", "Nicaragüense"),
        ("Nigerina", "Nigerina"),
        ("Nigeriana", "Nigeriana"),
        ("Noruega", "Noruega"),
        ("Neozelandesa", "Neozelandesa"),
        ("Omaní", "Omaní"),
        ("Neerlandesa", "Neerlandesa"),
        ("Pakistaní", "Pakistaní"),
        ("Palestina", "Palestina"),
        ("Panameña", "Panameña"),
        ("Papú", "Papú"),
        ("Paraguaya", "Paraguaya"),
        ("Peruana", "Peruana"),
        ("Polaca", "Polaca"),
        ("Portuguesa", "Portuguesa"),
        ("Puertorriqueña", "Puertorriqueña"),
        ("Británica", "Británica"),
        ("Checa", "Checa"),
        ("Dominicana", "Dominicana"),
        ("Ruandesa", "Ruandesa"),
        ("Rumana", "Rumana"),
        ("Rusa", "Rusa"),
        ("Salomonense", "Salomonense"),
        ("Samoana", "Samoana"),
        ("Senegalesa", "Senegalesa"),
        ("Serbia", "Serbia"),
        ("Seychellense", "Seychellense"),
        ("Sierraleonesa", "Sierraleonesa"),
        ("Singapurense", "Singapurense"),
        ("Siria", "Siria"),
        ("Somalí", "Somalí"),
        ("Srilanquesa", "Srilanquesa"),
        ("Suazilandesa", "Suazilandesa"),
        ("Sudafricana", "Sudafricana"),
        ("Sudanesa", "Sudanesa"),
        ("Sueca", "Sueca"),
        ("Suiza", "Suiza"),
        ("Surinamesa", "Surinamesa"),
        ("Tailandesa", "Tailandesa"),
        ("Tanzana", "Tanzana"),
        ("Tayika", "Tayika"),
        ("Togolesa", "Togolesa"),
        ("Tongana", "Tongana"),
        ("Trinitense", "Trinitense"),
        ("Tunecina", "Tunecina"),
        ("Turca", "Turca"),
        ("Ucraniana", "Ucraniana"),
        ("Ugandesa", "Ugandesa"),
        ("Uruguaya", "Uruguaya"),
        ("Uzbeka", "Uzbeka"),
        ("Venezolana", "Venezolana"),
        ("Vietnamita", "Vietnamita"),
        ("Yemení", "Yemení"),
        ("Zambiana", "Zambiana"),
        ("Zimbabuense", "Zimbabuense")
    ] 