"""add unique constraints to telefono and document_number

Revision ID: 2b80c44dbb13
Revises: 30e1d14de6a6
Create Date: 2025-09-04 09:04:57.013005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b80c44dbb13'
down_revision = '30e1d14de6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_document_number', ['document_number'])
        batch_op.create_unique_constraint('uq_user_telefono', ['telefono'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_telefono', type_='unique')
        batch_op.drop_constraint('uq_user_document_number', type_='unique')

    # ### end Alembic commands ###
