"""add document fields to beneficiario

Revision ID: 3002b1ad9c81
Revises: 3808abb53698
Create Date: 2025-09-05 08:37:28.926551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3002b1ad9c81'
down_revision = '3808abb53698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('document_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiario', schema=None) as batch_op:
        batch_op.drop_column('document_number')
        batch_op.drop_column('document_type')

    # ### end Alembic commands ###
