"""add document_number to user

Revision ID: 30e1d14de6a6
Revises: 3158e88b14e0
Create Date: 2025-09-04 08:54:44.577458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e1d14de6a6'
down_revision = '3158e88b14e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('document_number')

    # ### end Alembic commands ###
