"""add estado to archivo

Revision ID: 3808abb53698
Revises: 30e1d14de6a6
Create Date: 2025-09-04 09:40:53.282427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3808abb53698'
down_revision = '30e1d14de6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.drop_column('estado')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), nullable=True),
    sa.Column('apellido', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('ciudad', sa.VARCHAR(length=64), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=64), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('codigo_postal', sa.VARCHAR(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.DATE(), nullable=True),
    sa.Column('fecha_registro', sa.DATETIME(), nullable=True),
    sa.Column('ultimo_acceso', sa.DATETIME(), nullable=True),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.Column('dropbox_folder_path', sa.VARCHAR(), nullable=True),
    sa.Column('es_beneficiario', sa.BOOLEAN(), nullable=True),
    sa.Column('titular_id', sa.INTEGER(), nullable=True),
    sa.Column('rol', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nacionality', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), nullable=True),
    sa.Column('lector_extra_permissions', sa.TEXT(), nullable=True),
    sa.Column('dropbox_account_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('dropbox_cursor', sa.VARCHAR(length=500), nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=30), nullable=True),
    sa.Column('document_number', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['titular_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number', name='uq_user_document_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono', name='uq_user_telefono')
    )
    # ### end Alembic commands ###
