"""add alien_number to user

Revision ID: 3aaf4042c216
Revises: 3002b1ad9c81
Create Date: 2025-09-05 09:32:24.870573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aaf4042c216'
down_revision = '3002b1ad9c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alien_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('alien_number')

    # ### end Alembic commands ###
