"""agregar_campos_webhook_dropbox

Revision ID: 82f02500b67f
Revises: 98730ad8a261
Create Date: 2025-07-28 18:32:54.703966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f02500b67f'
down_revision = '98730ad8a261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dropbox_account_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('dropbox_cursor', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dropbox_cursor')
        batch_op.drop_column('dropbox_account_id')

    # ### end Alembic commands ###
