"""agregar_campo_lector_extra_permissions

Revision ID: 98730ad8a261
Revises: 411d0c499fef
Create Date: 2025-07-21 13:09:46.503023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98730ad8a261'
down_revision = '411d0c499fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lector_extra_permissions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lector_extra_permissions')

    # ### end Alembic commands ###
