"""agregando beneficiario

Revision ID: 9c105d792023
Revises: 209c7408cbaf
Create Date: 2025-07-13 14:06:40.528340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c105d792023'
down_revision = '209c7408cbaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_beneficiario', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('titular_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['titular_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('titular_id')
        batch_op.drop_column('es_beneficiario')

    # ### end Alembic commands ###
