"""agregar_campos_soft_delete

Revision ID: a129a6d26bdb
Revises: 82f02500b67f
Create Date: 2025-08-01 23:10:37.727198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a129a6d26bdb'
down_revision = '82f02500b67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('eliminado_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_archivo_eliminado_por', 'user', ['eliminado_por'], ['id'])

    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eliminado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('eliminado_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_folder_eliminado_por', 'user', ['eliminado_por'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_constraint('fk_folder_eliminado_por', type_='foreignkey')
        batch_op.drop_column('eliminado_por')
        batch_op.drop_column('fecha_eliminacion')
        batch_op.drop_column('eliminado')

    with op.batch_alter_table('archivo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_archivo_eliminado_por', type_='foreignkey')
        batch_op.drop_column('eliminado_por')
        batch_op.drop_column('fecha_eliminacion')
        batch_op.drop_column('eliminado')

    # ### end Alembic commands ###
