"""add_archivo_id_to_notification

Revision ID: a7e1c3b24337
Revises: 7b1a2c3d4e5f
Create Date: 2025-11-02 10:37:33.490986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e1c3b24337'
down_revision = '7b1a2c3d4e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notification_archivo', 'archivo', ['archivo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_archivo', type_='foreignkey')
        batch_op.drop_column('archivo_id')
    # ### end Alembic commands ###
