"""Add es_publica to Folder

Revision ID: c47521a9111b
Revises: b17582d75ec2
Create Date: 2025-07-15 09:20:56.013197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47521a9111b'
down_revision = 'b17582d75ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_publica', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folder', schema=None) as batch_op:
        batch_op.drop_column('es_publica')

    # ### end Alembic commands ###
