"""Initial migration with all models including dashboard and profile features

Revision ID: e6661792e40d
Revises: 
Create Date: 2025-07-17 09:54:43.588227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6661792e40d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('apellido', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('ciudad', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.String(length=64), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('dropbox_folder_path', sa.String(), nullable=True),
    sa.Column('es_beneficiario', sa.Boolean(), nullable=True),
    sa.Column('titular_id', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['titular_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('archivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('subcategoria', sa.String(length=100), nullable=False),
    sa.Column('dropbox_path', sa.String(length=500), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.Column('tamano', sa.Integer(), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficiario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('titular_id', sa.Integer(), nullable=False),
    sa.Column('dropbox_folder_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['titular_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dropbox_path', sa.String(), nullable=True),
    sa.Column('es_publica', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_leida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder_permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puede_ver', sa.Boolean(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_permiso')
    op.drop_table('user_activity_log')
    op.drop_table('notification')
    op.drop_table('folder')
    op.drop_table('beneficiario')
    op.drop_table('archivo')
    op.drop_table('user')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
