"""add_archivo_id_to_notification

Revision ID: ee0fc1e05e3d
Revises: a7e1c3b24337
Create Date: 2025-11-03 18:57:15.152815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0fc1e05e3d'
down_revision = 'a7e1c3b24337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar columna archivo_id a notification si no existe
    with op.batch_alter_table('notification', schema=None) as batch_op:
        try:
            batch_op.add_column(sa.Column('archivo_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_notification_archivo_id', 'archivo', ['archivo_id'], ['id'])
        except Exception as e:
            # Si la columna ya existe, ignorar el error
            print(f"Nota: archivo_id podría ya existir - {e}")
    
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.drop_index('ix_comentario_dropbox_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.create_index('ix_comentario_dropbox_path', ['dropbox_path'], unique=False)

    # ### end Alembic commands ###
